
export interface RobloxClass {
  name: string;
  category: string;
  description?: string;
  icon?: string;
  color?: string;
}

export const ROBLOX_CLASSES: RobloxClass[] = [
  // Common
  { name: 'Part', category: 'Common', icon: 'Box', color: '#00A2FF' },
  { name: 'Script', category: 'Common', icon: 'FileCode', color: '#00A2FF' },
  { name: 'LocalScript', category: 'Common', icon: 'FileCode2', color: '#FF4B4B' },
  { name: 'ModuleScript', category: 'Common', icon: 'FileJson', color: '#FFD700' },
  { name: 'Folder', category: 'Common', icon: 'Folder', color: '#FFD700' },
  { name: 'Tool', category: 'Common', icon: 'Wrench', color: '#AAAAAA' },
  { name: 'SpawnLocation', category: 'Common', icon: 'MapPin', color: '#32CD32' },
  { name: 'MeshPart', category: 'Common', icon: 'Component', color: '#00A2FF' },
  { name: 'Model', category: 'Common', icon: 'Package', color: '#FFD700' },
  { name: 'Configuration', category: 'Common', icon: 'Settings', color: '#AAAAAA' },
  { name: 'Backpack', category: 'Common', icon: 'Backpack', color: '#AAAAAA' },
  { name: 'Team', category: 'Common', icon: 'Users', color: '#FFD700' },
  { name: 'SpecialMesh', category: 'Common', icon: 'Box', color: '#00A2FF' },
  { name: 'BlockMesh', category: 'Common', icon: 'Box', color: '#00A2FF' },
  { name: 'CylinderMesh', category: 'Common', icon: 'Circle', color: '#00A2FF' },
  { name: 'CornerWedgePart', category: 'Common', icon: 'Box', color: '#00A2FF' },
  { name: 'TrussPart', category: 'Common', icon: 'Box', color: '#00A2FF' },
  { name: 'WedgePart', category: 'Common', icon: 'Box', color: '#00A2FF' },
  { name: 'WorldModel', category: 'Common', icon: 'Layers', color: '#FFD700' },
  { name: 'Camera', category: 'Common', icon: 'Camera', color: '#AAAAAA' },
  { name: 'StarterCharacterScripts', category: 'Scripting', icon: 'Folder', color: '#FF4500' },
  { name: 'StarterPlayerScripts', category: 'Scripting', icon: 'Folder', color: '#FF4500' },

  // Audio
  { name: 'Sound', category: 'Audio', icon: 'Volume2', color: '#FF69B4' },
  { name: 'AudioPlayer', category: 'Audio', icon: 'Play', color: '#FF69B4' },
  { name: 'AudioAnalyzer', category: 'Audio', icon: 'Activity', color: '#FF69B4' },
  { name: 'AudioEmitter', category: 'Audio', icon: 'Radio', color: '#FF69B4' },
  { name: 'AudioListener', category: 'Audio', icon: 'Ear', color: '#FF69B4' },
  { name: 'SoundGroup', category: 'Audio', icon: 'Layers', color: '#FF69B4' },
  { name: 'AudioChorus', category: 'Audio', icon: 'Waves', color: '#FF69B4' },
  { name: 'AudioCompressor', category: 'Audio', icon: 'Minimize', color: '#FF69B4' },
  { name: 'AudioDistortion', category: 'Audio', icon: 'Zap', color: '#FF69B4' },
  { name: 'AudioEcho', category: 'Audio', icon: 'Repeat', color: '#FF69B4' },
  { name: 'AudioFilter', category: 'Audio', icon: 'Filter', color: '#FF69B4' },
  { name: 'AudioFlanger', category: 'Audio', icon: 'Wind', color: '#FF69B4' },
  { name: 'AudioPitchShifter', category: 'Audio', icon: 'ArrowUpCircle', color: '#FF69B4' },
  { name: 'AudioReverb', category: 'Audio', icon: 'Maximize', color: '#FF69B4' },
  { name: 'AudioChannelMixer', category: 'Audio', icon: 'Sliders', color: '#FF69B4' },
  { name: 'AudioChannelSplitter', category: 'Audio', icon: 'Split', color: '#FF69B4' },
  { name: 'AudioDeviceInput', category: 'Audio', icon: 'Mic', color: '#FF69B4' },
  { name: 'AudioDeviceOutput', category: 'Audio', icon: 'Speaker', color: '#FF69B4' },
  { name: 'AudioFader', category: 'Audio', icon: 'Volume1', color: '#FF69B4' },
  { name: 'AudioGate', category: 'Audio', icon: 'Lock', color: '#FF69B4' },
  { name: 'AudioLimiter', category: 'Audio', icon: 'Minus', color: '#FF69B4' },
  { name: 'AudioSpeechToText', category: 'Audio', icon: 'Type', color: '#FF69B4' },
  { name: 'AudioTextToSpeech', category: 'Audio', icon: 'MessageSquare', color: '#FF69B4' },
  { name: 'AudioTremolo', category: 'Audio', icon: 'Activity', color: '#FF69B4' },
  { name: 'AudioEqualizer', category: 'Audio', icon: 'Filter', color: '#FF69B4' },
  { name: 'ChorusSoundEffect', category: 'Audio', icon: 'Waves', color: '#FF69B4' },
  { name: 'CompressorSoundEffect', category: 'Audio', icon: 'Minimize', color: '#FF69B4' },
  { name: 'DistortionSoundEffect', category: 'Audio', icon: 'Zap', color: '#FF69B4' },
  { name: 'EchoSoundEffect', category: 'Audio', icon: 'Repeat', color: '#FF69B4' },
  { name: 'EqualizerSoundEffect', category: 'Audio', icon: 'Filter', color: '#FF69B4' },
  { name: 'FlangeSoundEffect', category: 'Audio', icon: 'Wind', color: '#FF69B4' },
  { name: 'PitchShiftSoundEffect', category: 'Audio', icon: 'ArrowUpCircle', color: '#FF69B4' },
  { name: 'ReverbSoundEffect', category: 'Audio', icon: 'Maximize', color: '#FF69B4' },
  { name: 'TremoloSoundEffect', category: 'Audio', icon: 'Activity', color: '#FF69B4' },
  { name: 'Wire', category: 'Audio', icon: 'Spline', color: '#AAAAAA' },

  // Lighting
  { name: 'PointLight', category: 'Lighting', icon: 'Lightbulb', color: '#FFA500' },
  { name: 'SpotLight', category: 'Lighting', icon: 'Sun', color: '#FFA500' },
  { name: 'SurfaceLight', category: 'Lighting', icon: 'Lamp', color: '#FFA500' },

  // Environment
  { name: 'Atmosphere', category: 'Environment', icon: 'Cloud', color: '#87CEEB' },
  { name: 'Clouds', category: 'Environment', icon: 'Cloudy', color: '#87CEEB' },
  { name: 'Sky', category: 'Environment', icon: 'CloudSun', color: '#87CEEB' },
  { name: 'SunRaysEffect', category: 'Environment', icon: 'SunMedium', color: '#FFA500' },
  { name: 'Decal', category: 'Environment', icon: 'Image', color: '#87CEEB' },
  { name: 'Texture', category: 'Environment', icon: 'Grid', color: '#87CEEB' },
  { name: 'SurfaceAppearance', category: 'Environment', icon: 'Palette', color: '#87CEEB' },
  { name: 'Terrain', category: 'Environment', icon: 'Mountain', color: '#8BC34A' },
  { name: 'TerrainDetail', category: 'Environment', icon: 'Mountain', color: '#8BC34A' },
  { name: 'MaterialVariant', category: 'Environment', icon: 'Layers', color: '#8BC34A' },
  { name: 'PathfindingModifier', category: 'Environment', icon: 'Navigation', color: '#87CEEB' },
  { name: 'PathfindingLink', category: 'Environment', icon: 'Link', color: '#87CEEB' },

  // GUI
  { name: 'ScreenGui', category: 'GUI', icon: 'Monitor', color: '#00FF7F' },
  { name: 'BillboardGui', category: 'GUI', icon: 'StickyNote', color: '#00FF7F' },
  { name: 'SurfaceGui', category: 'GUI', icon: 'Square', color: '#00FF7F' },
  { name: 'Frame', category: 'GUI', icon: 'Square', color: '#00FF7F' },
  { name: 'ScrollingFrame', category: 'GUI', icon: 'MousePointer2', color: '#00FF7F' },
  { name: 'TextLabel', category: 'GUI', icon: 'Type', color: '#00FF7F' },
  { name: 'TextButton', category: 'GUI', icon: 'MousePointer', color: '#00FF7F' },
  { name: 'TextBox', category: 'GUI', icon: 'TextInput', color: '#00FF7F' },
  { name: 'ImageLabel', category: 'GUI', icon: 'Image', color: '#00FF7F' },
  { name: 'ImageButton', category: 'GUI', icon: 'ImagePlus', color: '#00FF7F' },
  { name: 'CanvasGroup', category: 'GUI', icon: 'Layers', color: '#00FF7F' },
  { name: 'ViewportFrame', category: 'GUI', icon: 'View', color: '#00FF7F' },
  { name: 'VideoFrame', category: 'GUI', icon: 'Video', color: '#00FF7F' },
  { name: 'UICorner', category: 'GUI', icon: 'Circle', color: '#00FF7F' },
  { name: 'UIGradient', category: 'GUI', icon: 'Palette', color: '#00FF7F' },
  { name: 'UIListLayout', category: 'GUI', icon: 'List', color: '#00FF7F' },
  { name: 'UIGridLayout', category: 'GUI', icon: 'Grid', color: '#00FF7F' },
  { name: 'UIPadding', category: 'GUI', icon: 'Maximize', color: '#00FF7F' },
  { name: 'UIStroke', category: 'GUI', icon: 'Pencil', color: '#00FF7F' },
  { name: 'UIScale', category: 'GUI', icon: 'Maximize', color: '#00FF7F' },
  { name: 'UIAspectRatioConstraint', category: 'GUI', icon: 'BoxSelect', color: '#00FF7F' },
  { name: 'UISizeConstraint', category: 'GUI', icon: 'Minimize', color: '#00FF7F' },
  { name: 'UITextSizeConstraint', category: 'GUI', icon: 'Type', color: '#00FF7F' },
  { name: 'PlayerGui', category: 'GUI', icon: 'Monitor', color: '#00FF7F' },

  // Constraints
  { name: 'Weld', category: 'Constraints', icon: 'Link', color: '#AAAAAA' },
  { name: 'WeldConstraint', category: 'Constraints', icon: 'Link2', color: '#AAAAAA' },
  { name: 'HingeConstraint', category: 'Constraints', icon: 'RotateCw', color: '#AAAAAA' },
  { name: 'BallSocketConstraint', category: 'Constraints', icon: 'CircleDot', color: '#AAAAAA' },
  { name: 'RopeConstraint', category: 'Constraints', icon: 'Spline', color: '#AAAAAA' },
  { name: 'SpringConstraint', category: 'Constraints', icon: 'Waves', color: '#AAAAAA' },
  { name: 'AlignOrientation', category: 'Constraints', icon: 'Compass', color: '#AAAAAA' },
  { name: 'AlignPosition', category: 'Constraints', icon: 'Target', color: '#AAAAAA' },
  { name: 'LinearVelocity', category: 'Constraints', icon: 'MoveRight', color: '#AAAAAA' },
  { name: 'AngularVelocity', category: 'Constraints', icon: 'RotateCcw', color: '#AAAAAA' },
  { name: 'CylindricalConstraint', category: 'Constraints', icon: 'Circle', color: '#AAAAAA' },
  { name: 'PrismaticConstraint', category: 'Constraints', icon: 'ArrowRightLeft', color: '#AAAAAA' },
  { name: 'UniversalConstraint', category: 'Constraints', icon: 'Globe', color: '#AAAAAA' },
  { name: 'TorsionSpringConstraint', category: 'Constraints', icon: 'RefreshCw', color: '#AAAAAA' },
  { name: 'Cable', category: 'Constraints', icon: 'Spline', color: '#AAAAAA' },

  // Physics
  { name: 'BodyVelocity', category: 'Physics', icon: 'FastForward', color: '#AAAAAA' },
  { name: 'BodyGyro', category: 'Physics', icon: 'RotateCw', color: '#AAAAAA' },
  { name: 'BodyPosition', category: 'Physics', icon: 'Target', color: '#AAAAAA' },
  { name: 'BodyAngularVelocity', category: 'Physics', icon: 'RotateCcw', color: '#AAAAAA' },
  { name: 'BodyThrust', category: 'Physics', icon: 'ArrowUp', color: '#AAAAAA' },
  { name: 'BodyForce', category: 'Physics', icon: 'Weight', color: '#AAAAAA' },

  // Values
  { name: 'StringValue', category: 'Values', icon: 'Type', color: '#9370DB' },
  { name: 'NumberValue', category: 'Values', icon: 'Hash', color: '#9370DB' },
  { name: 'IntValue', category: 'Values', icon: 'Binary', color: '#9370DB' },
  { name: 'BoolValue', category: 'Values', icon: 'CheckSquare', color: '#9370DB' },
  { name: 'Vector3Value', category: 'Values', icon: 'Box', color: '#9370DB' },
  { name: 'CFrameValue', category: 'Values', icon: 'Move', color: '#9370DB' },
  { name: 'Color3Value', category: 'Values', icon: 'Palette', color: '#9370DB' },
  { name: 'ObjectValue', category: 'Values', icon: 'Database', color: '#9370DB' },
  { name: 'RayValue', category: 'Values', icon: 'ArrowUpRight', color: '#9370DB' },
  { name: 'BrickColorValue', category: 'Values', icon: 'Palette', color: '#9370DB' },
  { name: 'AdGui', category: 'Advertising', icon: 'Monitor', color: '#00FF7F' },
  { name: 'StyleDerive', category: 'Style', icon: 'Palette', color: '#AAAAAA' },
  { name: 'StyleLink', category: 'Style', icon: 'Link', color: '#AAAAAA' },
  { name: 'StyleQuery', category: 'Style', icon: 'Search', color: '#AAAAAA' },
  { name: 'StyleRule', category: 'Style', icon: 'Settings', color: '#AAAAAA' },
  { name: 'StyleSheet', category: 'Style', icon: 'FileText', color: '#AAAAAA' },
  { name: 'ArcHandles', category: 'Decoration', icon: 'Move', color: '#FFD700' },
  { name: 'BoxHandleAdornment', category: 'Decoration', icon: 'Box', color: '#FFD700' },
  { name: 'ConeHandleAdornment', category: 'Decoration', icon: 'Triangle', color: '#FFD700' },
  { name: 'Input', category: 'Input', icon: 'Keyboard', color: '#AAAAAA' },
  { name: 'InputAction', category: 'Input', icon: 'Zap', color: '#AAAAAA' },
  { name: 'InputBinding', category: 'Input', icon: 'Link', color: '#AAAAAA' },
  { name: 'InputContext', category: 'Input', icon: 'Settings', color: '#AAAAAA' },
  { name: 'VideoDisplay', category: 'Media', icon: 'Monitor', color: '#FF69B4' },
  { name: 'VideoPlayer', category: 'Media', icon: 'Video', color: '#FF69B4' },
  { name: 'HapticEffect', category: 'System', icon: 'Smartphone', color: '#AAAAAA' },
  { name: 'MakeupDescription', category: 'System', icon: 'User', color: '#FFFFFF' },
  { name: 'AnimationConstraint', category: 'Constraints', icon: 'Activity', color: '#AAAAAA' },
  { name: 'Attachment', category: 'Constraints', icon: 'Anchor', color: '#AAAAAA' },
  { name: 'LineForce', category: 'Constraints', icon: 'Move', color: '#AAAAAA' },
  { name: 'NoCollisionConstraint', category: 'Constraints', icon: 'ShieldOff', color: '#AAAAAA' },
  { name: 'PlaneConstraint', category: 'Constraints', icon: 'Square', color: '#AAAAAA' },
  { name: 'RigidConstraint', category: 'Constraints', icon: 'Link', color: '#AAAAAA' },
  { name: 'RodConstraint', category: 'Constraints', icon: 'Spline', color: '#AAAAAA' },
  { name: 'Torque', category: 'Constraints', icon: 'RotateCw', color: '#AAAAAA' },
  { name: 'VectorForce', category: 'Constraints', icon: 'Move', color: '#AAAAAA' },
  { name: 'SwimController', category: 'Avatar', icon: 'Droplets', color: '#FFFFFF' },

  // Interaction
  { name: 'ClickDetector', category: 'Interaction', icon: 'MousePointerClick', color: '#FFD700' },
  { name: 'ProximityPrompt', category: 'Interaction', icon: 'Hand', color: '#FFD700' },
  { name: 'Seat', category: 'Interaction', icon: 'Armchair', color: '#FFD700' },
  { name: 'VehicleSeat', category: 'Interaction', icon: 'Car', color: '#FFD700' },
  { name: 'TouchTransmitter', category: 'Interaction', icon: 'Fingerprint', color: '#FFD700' },

  // Scripting
  { name: 'RemoteEvent', category: 'Scripting', icon: 'Zap', color: '#FF4500' },
  { name: 'RemoteFunction', category: 'Scripting', icon: 'ZapOff', color: '#FF4500' },
  { name: 'BindableEvent', category: 'Scripting', icon: 'Signal', color: '#FF4500' },
  { name: 'BindableFunction', category: 'Scripting', icon: 'SignalMedium', color: '#FF4500' },
  { name: 'UnreliableRemoteEvent', category: 'Scripting', icon: 'Zap', color: '#FF4500' },
  { name: 'PlayerScripts', category: 'Scripting', icon: 'FileCode', color: '#FF4500' },
  { name: 'TextChannel', category: 'Scripting', icon: 'MessageSquare', color: '#00BCD4' },
  { name: 'TextChatCommand', category: 'Scripting', icon: 'Command', color: '#00BCD4' },
  { name: 'Actor', category: 'Scripting', icon: 'Cpu', color: '#FF4500' },

  // Effects
  { name: 'ParticleEmitter', category: 'Effects', icon: 'Sparkles', color: '#FF8C00' },
  { name: 'Trail', category: 'Effects', icon: 'Wind', color: '#FF8C00' },
  { name: 'Beam', category: 'Effects', icon: 'Zap', color: '#FF8C00' },
  { name: 'Fire', category: 'Effects', icon: 'Flame', color: '#FF8C00' },
  { name: 'Smoke', category: 'Effects', icon: 'Cloud', color: '#FF8C00' },
  { name: 'Explosion', category: 'Effects', icon: 'Bomb', color: '#FF8C00' },
  { name: 'Highlight', category: 'Effects', icon: 'Sun', color: '#FF8C00' },
  { name: 'SelectionBox', category: 'Effects', icon: 'Focus', color: '#FF8C00' },
  { name: 'SelectionSphere', category: 'Effects', icon: 'Circle', color: '#FF8C00' },
  { name: 'ForceField', category: 'Effects', icon: 'Shield', color: '#FF8C00' },
  { name: 'Mesh', category: 'Effects', icon: 'Component', color: '#FF8C00' },

  // PostProcessing
  { name: 'BloomEffect', category: 'PostProcessing', icon: 'Sun', color: '#FFD700' },
  { name: 'BlurEffect', category: 'PostProcessing', icon: 'EyeOff', color: '#FFD700' },
  { name: 'ColorCorrectionEffect', category: 'PostProcessing', icon: 'Sliders', color: '#FFD700' },
  { name: 'DepthOfFieldEffect', category: 'PostProcessing', icon: 'Focus', color: '#FFD700' },

  // Avatar
  { name: 'Humanoid', category: 'Avatar', icon: 'User', color: '#FFFFFF' },
  { name: 'HumanoidDescription', category: 'Avatar', icon: 'UserCircle', color: '#FFFFFF' },
  { name: 'Animation', category: 'Avatar', icon: 'Activity', color: '#FFFFFF' },
  { name: 'AnimationController', category: 'Avatar', icon: 'Settings', color: '#FFFFFF' },
  { name: 'Animator', category: 'Avatar', icon: 'Play', color: '#FFFFFF' },
  { name: 'Accessory', category: 'Avatar', icon: 'Shirt', color: '#FFFFFF' },
  { name: 'Shirt', category: 'Avatar', icon: 'Shirt', color: '#FFFFFF' },
  { name: 'Pants', category: 'Avatar', icon: 'UserSquare', color: '#FFFFFF' },
  { name: 'BodyColors', category: 'Avatar', icon: 'Palette', color: '#FFFFFF' },
  { name: 'ShirtGraphic', category: 'Avatar', icon: 'Image', color: '#FFFFFF' },
  { name: 'CharacterMesh', category: 'Avatar', icon: 'Component', color: '#FFFFFF' },
  { name: 'Bone', category: 'Avatar', icon: 'Bone', color: '#FFFFFF' },
  { name: 'IKControl', category: 'Avatar', icon: 'Activity', color: '#FFFFFF' },
  { name: 'FaceControls', category: 'Avatar', icon: 'Smile', color: '#FFFFFF' },
  { name: 'WrapLayer', category: 'Avatar', icon: 'Layers', color: '#FFFFFF' },
  { name: 'WrapTarget', category: 'Avatar', icon: 'Target', color: '#FFFFFF' },
  { name: 'AnimationTrack', category: 'Avatar', icon: 'Activity', color: '#FFFFFF' },
  { name: 'KeyframeSequence', category: 'Avatar', icon: 'List', color: '#FFFFFF' },
  { name: 'Keyframe', category: 'Avatar', icon: 'Circle', color: '#FFFFFF' },
  { name: 'Pose', category: 'Avatar', icon: 'User', color: '#FFFFFF' },
  { name: 'AirController', category: 'Avatar', icon: 'Wind', color: '#FFFFFF' },
  { name: 'BuoyancySensor', category: 'Avatar', icon: 'Droplets', color: '#FFFFFF' },
  { name: 'ClimbController', category: 'Avatar', icon: 'ArrowUpCircle', color: '#FFFFFF' },
  { name: 'ControllerManager', category: 'Avatar', icon: 'Settings', color: '#FFFFFF' },
  { name: 'ControllerPartSensor', category: 'Avatar', icon: 'Sensor', color: '#FFFFFF' },

  // Services
  { name: 'Workspace', category: 'Services', icon: 'Globe', color: '#4CAF50' },
  { name: 'Camera', category: 'Common', icon: 'Camera', color: '#AAAAAA' },
  { name: 'Terrain', category: 'Environment', icon: 'Mountain', color: '#8BC34A' },
  { name: 'SpawnLocation', category: 'Common', icon: 'MapPin', color: '#32CD32' },
  { name: 'Part', category: 'Common', icon: 'Box', color: '#00A2FF' },
  { name: 'Players', category: 'Services', icon: 'Users', color: '#2196F3' },
  { name: 'Lighting', category: 'Services', icon: 'Sun', color: '#FFEB3B' },
  { name: 'MaterialService', category: 'Services', icon: 'Layers', color: '#8BC34A' },
  { name: 'NetworkClient', category: 'Services', icon: 'Globe', color: '#4CAF50' },
  { name: 'ClientReplicator', category: 'Services', icon: 'Cpu', color: '#607D8B' },
  { name: 'ReplicatedFirst', category: 'Services', icon: 'Zap', color: '#9C27B0' },
  { name: 'ReplicatedStorage', category: 'Services', icon: 'Database', color: '#03A9F4' },
  { name: 'StringValue', category: 'Values', icon: 'Hash', color: '#9370DB' },
  { name: 'ServerScriptService', category: 'Services', icon: 'Cpu', color: '#607D8B' },
  { name: 'ServerStorage', category: 'Services', icon: 'Database', color: '#9E9E9E' },
  { name: 'StarterGui', category: 'Services', icon: 'Monitor', color: '#E91E63' },
  { name: 'StarterPack', category: 'Services', icon: 'Package', color: '#FF9800' },
  { name: 'StarterPlayer', category: 'Services', icon: 'User', color: '#3F51B5' },
  { name: 'StarterCharacterScripts', category: 'Scripting', icon: 'Folder', color: '#FF4500' },
  { name: 'StarterPlayerScripts', category: 'Scripting', icon: 'Folder', color: '#FF4500' },
  { name: 'Teams', category: 'Services', icon: 'Shield', color: '#F44336' },
  { name: 'SoundService', category: 'Services', icon: 'Music', color: '#4CAF50' },
  { name: 'TextChatService', category: 'Services', icon: 'MessageSquare', color: '#0097A7' },
  { name: 'ChatWindowConfiguration', category: 'GUI', icon: 'Monitor', color: '#00FF7F' },
  { name: 'ChatInputBarConfiguration', category: 'GUI', icon: 'TextInput', color: '#00FF7F' },
  { name: 'ChannelTabsConfiguration', category: 'GUI', icon: 'List', color: '#00FF7F' },
  { name: 'BubbleChatConfiguration', category: 'GUI', icon: 'MessageSquare', color: '#00FF7F' },

  // Localization
  { name: 'LocalizationTable', category: 'Localization', icon: 'Globe', color: '#795548' },

  // Sensors
  { name: 'AtmosphereSensor', category: 'Sensors', icon: 'Cloud', color: '#87CEEB' },
  { name: 'FluidForceSensor', category: 'Sensors', icon: 'Droplets', color: '#87CEEB' },
  { name: 'GroundController', category: 'Sensors', icon: 'Move', color: '#8BC34A' },
];

export const CATEGORIES = [
  'Common',
  'Audio',
  'Lighting',
  'Environment',
  'GUI',
  'Constraints',
  'Physics',
  'Values',
  'Interaction',
  'Scripting',
  'Effects',
  'PostProcessing',
  'Avatar',
  'Services',
  'Localization',
  'Sensors',
  'Advertising',
  'Style',
  'Decoration',
  'Input',
  'Media',
  'System'
];

export const OBJECT_CATEGORIES = [
  { name: 'Thường Sử Dụng', classes: ROBLOX_CLASSES.filter(c => c.category === 'Common').map(c => c.name) },
  { name: 'Âm Thanh', classes: ROBLOX_CLASSES.filter(c => c.category === 'Audio').map(c => c.name) },
  { name: 'Ánh Sáng', classes: ROBLOX_CLASSES.filter(c => c.category === 'Lighting').map(c => c.name) },
  { name: 'Avatar', classes: ROBLOX_CLASSES.filter(c => c.category === 'Avatar').map(c => c.name) },
  { name: 'Bản Địa Hóa', classes: ROBLOX_CLASSES.filter(c => c.category === 'Localization').map(c => c.name) },
  { name: 'Bộ Phận', classes: ROBLOX_CLASSES.filter(c => ['Common', 'Decoration'].includes(c.category) && c.name.toLowerCase().includes('part')).map(c => c.name) },
  { name: 'Cảm Biến', classes: ROBLOX_CLASSES.filter(c => c.category === 'Sensors').map(c => c.name) },
  { name: 'Chưa được phân loại', classes: ROBLOX_CLASSES.filter(c => ['Physics', 'PostProcessing', 'Services', 'Media', 'System'].includes(c.category)).map(c => c.name) },
  { name: 'Đầu Vào', classes: ROBLOX_CLASSES.filter(c => c.category === 'Input').map(c => c.name) },
  { name: 'Đồ Trang Trí', classes: ROBLOX_CLASSES.filter(c => c.category === 'Decoration' && !c.name.toLowerCase().includes('part')).map(c => c.name) },
  { name: 'Giá Trị', classes: ROBLOX_CLASSES.filter(c => c.category === 'Values').map(c => c.name) },
  { name: 'Giao Diện 3D', classes: ROBLOX_CLASSES.filter(c => c.category === 'GUI' && c.name.toLowerCase().includes('3d')).map(c => c.name) },
  { name: 'GUI', classes: ROBLOX_CLASSES.filter(c => c.category === 'GUI' && !c.name.toLowerCase().includes('3d')).map(c => c.name) },
  { name: 'Hiệu Ứng', classes: ROBLOX_CLASSES.filter(c => c.category === 'Effects' && !c.name.toLowerCase().includes('animation')).map(c => c.name) },
  { name: 'Hiệu Ứng Động', classes: ROBLOX_CLASSES.filter(c => c.category === 'Effects' && c.name.toLowerCase().includes('animation')).map(c => c.name) },
  { name: 'Mesh', classes: ROBLOX_CLASSES.filter(c => c.name.toLowerCase().includes('mesh')).map(c => c.name) },
  { name: 'Môi Trường', classes: ROBLOX_CLASSES.filter(c => c.category === 'Environment' && !c.name.toLowerCase().includes('world')).map(c => c.name) },
  { name: 'Quảng Cáo', classes: ROBLOX_CLASSES.filter(c => c.category === 'Advertising').map(c => c.name) },
  { name: 'Ràng Buộc', classes: ROBLOX_CLASSES.filter(c => c.category === 'Constraints').map(c => c.name) },
  { name: 'Tạo Kiểu', classes: ROBLOX_CLASSES.filter(c => c.category === 'Style').map(c => c.name) },
  { name: 'Thế Giới', classes: ROBLOX_CLASSES.filter(c => c.category === 'Environment' && c.name.toLowerCase().includes('world')).map(c => c.name) },
  { name: 'Tin Nhắn Văn Bản', classes: ROBLOX_CLASSES.filter(c => c.category === 'Scripting' && c.name.toLowerCase().includes('text')).map(c => c.name) },
  { name: 'Tương Tác', classes: ROBLOX_CLASSES.filter(c => c.category === 'Interaction').map(c => c.name) },
  { name: 'Viết Kịch Bản', classes: ROBLOX_CLASSES.filter(c => c.category === 'Scripting' && !c.name.toLowerCase().includes('text')).map(c => c.name) },
];
